apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.appName}}-{{.Values.envName}}-config
  namespace: {{.Values.namespace}}
data:
  AWS_ACCESS_KEY_ID: {{.Values.awsAccessKeyId}}
  AWS_SECRET_ACCESS_KEY: {{.Values.awsSecretAccessKey}}
  AWS_REGION: {{.Values.awsRegion}}
  AWS_PROFILE: {{.Values.awsProfile}}
  DEST_DB_HOST: {{.Values.destDbHost}}
  DEST_DB_NAME: {{.Values.destDbName}}
  DEST_DB_PASS: {{.Values.destDbPass}}
  DEST_DB_USER: {{.Values.destDbUser}}
  DEST_S3_BUCKET: {{.Values.destS3Bucket}}
  DEST_DB_PORT: {{.Values.destDbPort}}
  DEST_CLOUDFRONT_ID: {{.Values.destCloudfrontId}}
  SOURCE_DB_HOST: {{.Values.sourceDbHost}}
  SOURCE_DB_NAME: {{.Values.sourceDbName}}
  SOURCE_DB_PASS: {{.Values.sourceDbPass}}
  SOURCE_DB_USER: {{.Values.sourceDbUser}}
  SOURCE_DB_PORT: {{.Values.sourceDbPort}}
  SOURCE_S3_BUCKET: {{.Values.sourceS3Bucket}}
  SOURCE_EXCLUDE_TABLE: {{.Values.sourceExcludeTable}}
