apiVersion: batch/v1beta1
kind: Job
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.appName}}-{{.Values.envName}}-cron
spec:
  template:
    spec:
      containers:
      - name: {{.Values.appName}}-{{.Values.envName}}-cron
        image: {{.Values.artifactImage}}
        securityContext:
          runAsUser: 0
        envFrom:
        - configMapRef:
            name: {{.Values.appName}}-{{.Values.envName}}-config
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
      restartPolicy: Never
  backoffLimit: 4
